name: Publish to NPM

on:
  workflow_dispatch: ~
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  NPM_TOKEN: ${{ secrets.NPM_PAT }}
  VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
  OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm build

      - name: Publish to VS Code Marketplace
        if: ${{ env.VSCE_PAT != '' }}
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          packagePath: ./packages/vscode
          dependencies: false

      - name: Publish to Open VSX
        if: ${{ env.OPEN_VSX_TOKEN != '' }}
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          registryUrl: https://open-vsx.org
          packagePath: ./packages/vscode

      - name: pnpm publish
        working-directory: ./packages/language-server
        run: |
            npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
            pnpm publish --no-git-checks
